#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-prawn
Version  : 2.0.2
Release  : 6
URL      : https://rubygems.org/downloads/prawn-2.0.2.gem
Source0  : https://rubygems.org/downloads/prawn-2.0.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 Ruby
BuildRequires : ruby
BuildRequires : rubygem-mocha
BuildRequires : rubygem-pdf-inspector
BuildRequires : rubygem-prawn-manual_builder
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-ttfunk
BuildRequires : rubygem-yard

%description
No detailed description available

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n prawn-2.0.2
gem spec %{SOURCE0} -l --ruby > rubygem-prawn.gemspec

%build
gem build rubygem-prawn.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
prawn-2.0.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/prawn-2.0.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/GPLv2
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/GPLv3
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Courier-Bold.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Courier-BoldOblique.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Courier-Oblique.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Courier.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Helvetica-Bold.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Helvetica-BoldOblique.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Helvetica-Oblique.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Helvetica.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/MustRead.html
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Symbol.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Times-Bold.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Times-BoldItalic.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Times-Italic.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/Times-Roman.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/fonts/ZapfDingbats.afm
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/16bit.alpha
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/16bit.color
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/16bit.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/arrow.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/arrow2.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/dice.alpha
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/dice.color
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/dice.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/dice_interlaced.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/fractal.jpg
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/indexed_color.dat
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/indexed_color.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/letterhead.jpg
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/license.md
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/page_white_text.alpha
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/page_white_text.color
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/page_white_text.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/pal_bk.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/pigs.jpg
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/prawn.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/ruport.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/ruport_data.dat
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/ruport_transparent.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/ruport_type0.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/stef.jpg
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/tru256.bmp
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/web-links.dat
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/images/web-links.png
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/complex_template.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/contains_ttf_font.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/encrypted.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/form.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/hexagon.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/indirect_reference.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/multipage_template.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/nested_pages.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/page_without_mediabox.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/resources_as_indirect_object.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/two_hexagons.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/pdfs/version_1_6.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/data/shift_jis_text.txt
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/document.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/document/bounding_box.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/document/column_box.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/document/internals.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/document/span.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/encoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/font.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/font/afm.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/font/dfont.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/font/ttf.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/font_metric_cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/graphics.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/graphics/cap_style.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/graphics/color.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/graphics/dash.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/graphics/join_style.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/graphics/patterns.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/graphics/transformation.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/graphics/transparency.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/grid.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/image_handler.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/images.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/images/image.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/images/jpg.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/images/png.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/measurement_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/measurements.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/outline.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/repeater.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/security.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/security/arcfour.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/soft_mask.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/stamp.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/text/box.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/text/formatted.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/text/formatted/arranger.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/text/formatted/box.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/text/formatted/fragment.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/text/formatted/line_wrap.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/text/formatted/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/text/formatted/wrap.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/utilities.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/lib/prawn/view.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/absolute_position.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/basic_concepts/adding_pages.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/basic_concepts/basic_concepts.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/basic_concepts/creation.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/basic_concepts/cursor.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/basic_concepts/measurement.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/basic_concepts/origin.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/basic_concepts/other_cursor_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/basic_concepts/view.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/bounding_box/bounding_box.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/bounding_box/bounds.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/bounding_box/canvas.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/bounding_box/creation.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/bounding_box/indentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/bounding_box/nesting.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/bounding_box/russian_boxes.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/bounding_box/stretchy.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/contents.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/cover.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/document_and_page_options/background.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/document_and_page_options/document_and_page_options.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/document_and_page_options/metadata.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/document_and_page_options/page_margins.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/document_and_page_options/page_size.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/document_and_page_options/print_scaling.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/example_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/circle_and_ellipse.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/color.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/common_lines.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/fill_and_stroke.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/fill_rules.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/gradients.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/graphics.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/line_width.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/lines_and_curves.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/polygon.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/rectangle.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/rotate.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/scale.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/soft_masks.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/stroke_cap.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/stroke_dash.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/stroke_join.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/translate.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/graphics/transparency.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/how_to_read_this_manual.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/images/absolute_position.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/images/fit.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/images/horizontal.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/images/images.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/images/plain_image.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/images/scale.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/images/vertical.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/images/width_and_height.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/layout/boxes.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/layout/content.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/layout/layout.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/layout/simple_grid.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/outline/add_subsection_to.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/outline/insert_section_after.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/outline/outline.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/outline/sections_and_pages.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/repeatable_content/alternate_page_numbering.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/repeatable_content/page_numbering.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/repeatable_content/repeatable_content.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/repeatable_content/repeater.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/repeatable_content/stamp.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/security/encryption.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/security/permissions.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/security/security.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/table.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/alignment.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/color.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/column_box.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/fallback_fonts.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/font.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/font_size.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/font_style.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/formatted_callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/formatted_text.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/free_flowing_text.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/inline.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/kerning_and_character_spacing.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/leading.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/line_wrapping.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/paragraph_indentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/positioned_text.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/registering_families.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/rendering_and_color.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/right_to_left_text.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/rotation.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/single_usage.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/text_box_excess.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/text_box_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/text_box_overflow.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/utf8.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/manual/text/win_ansi_charset.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/prawn.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/acceptance/png.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/annotations_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/bounding_box_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/column_box_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/data/curves.pdf
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/destinations_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/document_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/extensions/encoding_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/extensions/mocha.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/font_metric_cache_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/font_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/formatted_text_arranger_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/formatted_text_box_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/formatted_text_fragment_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/graphics_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/grid_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/image_handler_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/images_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/inline_formatted_text_parser_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/jpg_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/line_wrap_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/measurement_units_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/outline_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/png_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/reference_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/repeater_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/security_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/soft_mask_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/span_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/stamp_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/stroke_styles_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/text_at_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/text_box_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/text_rendering_mode_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/text_spacing_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/text_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/text_with_inline_formatting_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/transparency_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-2.0.2/spec/view_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/prawn-2.0.2.gemspec
